server:
  max-http-header-size: 8192
  port: 9091
logging:
  level:
    com:
      tct: debug
      tct.data.dao: debug
    root: info
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    name: my-blog-datasource
    url: jdbc:mysql://172.51.216.118:3306/processengine?serverTimezone=GMT%2B8&useSSL=FALSE&useUnicode=true&characterEncoding=utf-8&autoReconnect=true&allowMultiQueries=true
    username: root
    password: mysql
  rabbitmq:
    addresses: 172.51.216.117:5672
    #username: admin
    #password: admin
    listener:
      simple:
        acknowledge-mode: manual #手动签收
mybatis-plus:
  type-aliases-package: com.tct.data
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      table-prefix: tb_
      ##update-strategy: ignored
    banner: false
queue:
  apply: tct.apply
  feedback: tct.feedback